language: python
python:
  - 2.7
os:
  - linux
addons:
  apt:
    packages:
    - sqlite3
    sources:
    - travis-ci/sqlite3
before_install:
  - chmod +x devtools/travis-ci/chimera.sh
  - chmod +x devtools/travis-ci/miniconda.sh
  # Chimera:
  - devtools/travis-ci/chimera.sh
  # Miniconda:
  - devtools/travis-ci/miniconda.sh
install:
  # Configure conda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes
  - conda config --remove-key channels || true
  - conda config --add channels defaults
  - conda config --add channels insilichem
  - conda activate
  # Install Gaudi, Pychimera and Pytest
  - conda install -c omnia -c salilab -c insilichem -c bioconda gaudi
  - conda install -c insilichem pychimera pytest
  - export CHIMERADIR="$HOME/chimera"
  # Install PGaudi
  - pip install -i https://test.pypi.org/simple/ pgaudi
script:
  # Check package
  - cd tests
  - python run_test.py